### ISSUE TITLE
Switching between Svelte files and other file types lead to an annoying error

### ISSUE THREAD

**Issue by nima-dvlp** [coc-extensions/coc-svelte#55]
## Description
Trying to type `/` on any file type except for the Svelte files, lead to this error at the bottom of the screen :

```
[coc.nvim]: UnhandledRejection: Request html/tag failed with message: Cannot call methods on an unopened document
Error: Request html/tag failed with message: Cannot call methods on an unopened document
    at gu (/home/nima/.local/share/nvim/plugged/coc.nvim/build/index.js:38:224)
    at bp (/home/nima/.local/share/nvim/plugged/coc.nvim/build/index.js:37:11261)
    at Immediate.<anonymous> (/home/nima/.local/share/nvim/plugged/coc.nvim/build/index.js:37:11111)
    at processImmediate (node:internal/timers:466:21)
```

## How to reproduce :
Open a svelte file(activate Svelte LSP), open another file type(ts, js, json, anything except svelte), then try to issue `/`, this error hits, and it's so destructive!

## What it is
I think this is how you try to handle closing tags like below:
```svelte
<SvelteComponent>    </
<!--                  ^ here / issued -->
```

**Comment by freddyshim** [comment]
I'm experiencing the same issue and it's very annoying. Can we get this fix merged to master?
