### ISSUE TITLE
coc-svelte not work, Cannot read properties of undefined (reading 'debug')

### ISSUE THREAD

**Issue by sleep2death** [coc-extensions/coc-svelte#59]
vim version: NVIM v0.7.2
node version: v18.9.0
coc.nvim version: 0.0.82-488d6ae7 2022-09-22 01:50:53 +0800
coc.nvim directory: /Users/aspirin2d/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2022-09-22T23:12:02.827 INFO (pid:12804) [plugin] - coc.nvim initialized with node: v18.9.0 after 23ms
2022-09-22T23:12:10.300 INFO (pid:12804) [attach] - receive notification: showInfo []
2022-09-22T23:13:07.993 ERROR (pid:12804) [language-client-client] - Server svelte initialization failed. Xm [Error]: Request initialize failed with message: Cannot read properties of undefined (reading 'debug')
    at Fe (/Users/aspirin2d/.local/share/nvim/plugged/coc.nvim/build/index.js:25:233)
    at Ni (/Users/aspirin2d/.local/share/nvim/plugged/coc.nvim/build/index.js:24:6872)
    at Immediate.<anonymous> (/Users/aspirin2d/.local/share/nvim/plugged/coc.nvim/build/index.js:24:6719)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32603,
  data: undefined
}

vim :check health

coc: health#coc#check
========================================================================
  - OK: nvim version satisfied
  - OK: Environment check passed
  - WARNING: pyx command not work, some extensions may fail to work, checkout ":help pythonx"
  - WARNING: Install pynvim by command: pip install pynvim --upgrade
  - OK: Javascript bundle build/index.js found
  - OK: Service started

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - WARNING: Could not load Python 3:
    /usr/bin/python3 does not have the "neovim" module.
    python3.10 not found in search path or not executable.
    python3.9 not found in search path or not executable.
    python3.8 not found in search path or not executable.
    python3.7 not found in search path or not executable.
    python not found in search path or not executable.
    - ADVICE:
      - See :help provider-python for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
  - INFO: Executable: Not found

## Python virtualenv
  - OK: no $VIRTUAL_ENV

**Comment by sparkcanon** [comment]
I was about to make the same report. I have the same issue on vim 9.0.520

**Comment by 3ximus** [comment]
I had a similar issue
```
Cannot read properties of undefined (reading 'warnings') (svelte)
```
It comes from using svelte 5. The dependencies of this plugin don't support it yet I believe.
There's currently a PR to solve the issue:
https://github.com/coc-extensions/coc-svelte/pull/69
